config/routes.rb
Rails.application.routes.draw do
  get '/pages/:name' => 'pages#show', as: 'page'
  resources :sessions
  resources :secrets
  root to: 'pages#show', name: "home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gateway_connector.rb
#
## Helps with the OIDC flow to TruGateway
class GatewayConnector
  attr_accessor :session_nonce, :session_state, :client_id, :redirect_uri,
                :discovery_url, :auth_url

  def initialize(options: {}, client: nil, jwk_set: nil, jwt_decoder: nil)
    @client = client || HTTParty
    @jwk_set = jwk_set || JSON::JWK::Set
    @jwt_decoder = jwt_decoder || JSON::JWT
    options.symbolize_keys! # we're in rails
    validate_options(options)
    assign_options(options)
    assign_auth_url
  end

  def decode(token = nil)
    raise 'JWT is required' unless token
    jwks = @client.get(@oidc_config[:jwks_uri]).response.body
    jwks_set = @jwk_set.new(
      JSON.parse(jwks)
    )

    decoded = @jwt_decoder.decode(token, jwks_set)
    validate_token(decoded)
    decoded
  end

  private

  def validate_options(options)
    raise 'redirect URI is required' unless options[:redirect_uri]
    raise 'client ID is required' unless options[:client_id]
    raise 'discovery URL is required' unless options[:discovery_url]
  end

  def assign_options(options)
    @client_id     = options[:client_id]
    @redirect_uri  = options[:redirect_uri]
    @discovery_url = options[:discovery_url]
    @session_nonce = options[:session_nonce]
    @session_state = options[:session_state]
  end

  def assign_auth_url
    @oidc_config = auto_configure_oidc
    @auth_url = @oidc_config[:auth_url]
  end

  def validate_token(decoded)
    validate_content_presence(decoded)
    validate_content_matches(decoded)
    validate_timeliness(decoded)
  end

  def validate_timeliness(decoded)
    raise 'Invalid Token: not yet issued' unless
      decoded[:iat].between?(30.seconds.ago.to_i, Time.now.to_i)
    raise 'Invalid Token: token has expired' unless
      decoded[:exp] > Time.now.to_i
  end

  def validate_content_matches(decoded)
    raise 'Invalid Token: audience/client id mismatch' unless
      decoded[:aud] == @oidc_config[:client_id]
    raise 'Invalid Token: nonce mismatch' unless
      decoded[:nonce] == @session_nonce
  end

  def validate_content_presence(decoded)
    raise 'Invalid Token: missing audience' unless
      decoded[:aud].present?
    raise 'Invalid Token: missing subject' unless
      decoded[:sub].present?
  end

  def auto_configure_oidc
    JSON.parse(@client.get(@discovery_url).response.body)
        .merge('client_id' => @client_id)
        .symbolize_keys!
  end
end

app/models/hashed_email.rb
require 'digest'

class HashedEmail
  def initialize(email = '')
    @email = Digest::SHA256.hexdigest(email.downcase.strip)
  end

  def to_s
    @email
  end
end

app/models/secret.rb
require 'digest'

##
# A Secret
class Secret < ApplicationRecord
  before_save :hash_email, :default_expiration

  validates :recipient_email, presence: true

  def to_param
    id
  end

  private

  def hash_email
    self.recipient_email = HashedEmail.new(recipient_email).to_s
  end

  def default_expiration
    self.expires_at = Time.now + 1.hour if expires_at.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  force_ssl
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :verify_page

  def show
    @root_status = 'active' if @page == 'home'
    @about_status = 'active' if @page == 'about'
    render @page
  end

  private

  def verify_page
    # redirect_to root_path unless valid_pages.include?(params[:name])
    @page = params[:name]
  end

  def valid_pages
    %w[about home]
  end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController

  before_action :configure_connector, only: %i[show]
  before_action :reset_session, only: [:show]

  def index
    @list_secrets_status = 'active'
    @secrets = Secret.where(recipient_email: session[:email]).where(['expires_at > ?', Time.now]).order("expires_at DESC")
    session[:email] = nil
  end

  def new
    @new_secret_status = 'active'
    @secret = Secret.new
  end

  def create
    @secret = Secret.new(secret_params)
    @email = params[:secret][:recipient_email].downcase.strip

    if @secret.save
      flash[:error] = nil
      render 'create'
    else
      flash[:error] = "A recipient email is required."
      @recipient_email_valid_class = 'is-invalid'
      render 'new'
    end
  end

  def show
    @client_id    = @gateway_connector.client_id
    @auth_url     = @gateway_connector.auth_url
    @nonce        = @gateway_connector.session_nonce
    @state        = @gateway_connector.session_state
    @redirect_uri = @gateway_connector.redirect_uri
    @oidc_form_action = Rails.env.development? ? 'https://gateway.staging.trusona.net/oidc' : 'https://gateway.trusona.net/oidc'
  end

  private

  def secret_params
    params.require(:secret).permit(:recipient_email, :secret, :expires_at)
  end

   def configure_connector
    state = session[:session_state] ||= SecureRandom.uuid
    nonce = session[:session_nonce] ||= SecureRandom.uuid
    options = {
      client_id: ENV['TRUSONA_CLIENT_ID'],
      redirect_uri: sessions_url,
      discovery_url: ENV['TRUSONA_DISCOVERY_URL'],
      session_state: state,
      session_nonce: nonce
    }
    @gateway_connector = GatewayConnector.new(options: options)
  end
end

app/controllers/sessions_controller.rb
require 'digest'

class SessionsController < ApplicationController
  before_action :reset_session, except: [:create]
  before_action :configure_connector, only: %i[new create]
  skip_before_action :verify_authenticity_token

  def new
    @client_id    = @gateway_connector.client_id
    @auth_url     = @gateway_connector.auth_url
    @nonce        = @gateway_connector.session_nonce
    @state        = @gateway_connector.session_state
    @redirect_uri = @gateway_connector.redirect_uri
    @oidc_form_action = Rails.env.development? ? 'https://gateway.staging.trusona.net/oidc' : 'https://gateway.trusona.net/oidc'
  end

  def create
    Rails.logger.debug(params[:id_token])
    id_token = @gateway_connector.decode(params[:id_token])
    Rails.logger.debug(id_token)
    session['email'] = HashedEmail.new(id_token[:email]).to_s
    redirect_to secrets_url
  end

  private

  def configure_connector
    state = session[:session_state] ||= SecureRandom.uuid
    nonce = session[:session_nonce] ||= SecureRandom.uuid
    options = {
      client_id: ENV['TRUSONA_CLIENT_ID'],
      redirect_uri: sessions_url,
      discovery_url: ENV['TRUSONA_DISCOVERY_URL'],
      session_state: state,
      session_nonce: nonce
    }
    @gateway_connector = GatewayConnector.new(options: options)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_logo
    image_tag(
      "secret_snippet_logo.svg",
      class: "d-inline-block align-top",
      width: 30,
      height: 30
    )
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
  def random_funny_email_address
    %w[
      george.washington@usa.gov
      monster@cook.ie
      moe@moestavern.us
      ferris@saveferris.org
      dracula@redcross.org
      bugs@carrots.co
      fred@yabbadabba.do
      alvin@thechimpmunks.net
      hank@striklandpropane.us
      homer.simpson@springfieldnuclear.com
      wile.e.coyote@acme.com
      bob@squarepants.net
      george.jetson@spacelys.sprockets
    ].shuffle.first
  end

  def expires_at_options
    options_for_select(
      [
        ['1 Hour', (Time.now + 1.hour)], ['1 Day', (Time.now + 1.day)], ['1 Week', (Time.now + 1.week)]
      ],
      (Time.now + 1.hour)
    )
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-78648-28"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-78648-28');
    </script>
    <title>Securely send secret snippets. It's simple!</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary mb-5">
      <%= link_to "#{navbar_logo} Secret Snippet".html_safe, root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= @root_status %>">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= @new_secret_status %>">
            <%= link_to "Create a Secret", new_secret_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= @list_secrets_status %>">
            <%= link_to "My secrets", secrets_path, class: "nav-link"%>
          </li>
          <li class="nav-item <%= @about_status %>">
            <%= link_to "How it Works", page_path(name: "about"), class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted mb-0">
        <img src="https://travis-ci.org/clayton/secret_snippet.svg?branch=master" alt=""> <br>
        &copy; 2018 &mdash; Built for Trusona's May 2018 "Lab Day." Source available on <a href="https://github.com/clayton/secret_snippet">GitHub</a>. Built with <a href="https://www.trusona.com/">Trusona</a>. Inspired by <a href="https://onetimesecret.com/">One Time Secret</a>.
        Download <a href="https://itunes.apple.com/us/app/trusona/id1052983449?mt=8">Trusona for iOS</a> or <a href="https://play.google.com/store/apps/details?id=com.trusona.trusona&amp;pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1">Trusona for Android</a>.</p>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-md-6">
  <h1>What is Secret Snippet?</h1>
  <p>Secret Snippet uses the award winning <a href="https://www.trusona.com">Trusona</a> mobile app and service to help you quickly and easily share passwords, secret links, API keys and other things that usually end up in email, instant messages or written down on a piece of paper.</p>
  <h2>FAQ</h2>
  <dl>
    <dt>Who created Secret Snippet?</dt>
    <dd>Secret Snippet was created during Trusona's May 2018 "Lab Day" by Clayton Lengel-Zigich and David Foster. It's an experimental, fun, free and definitely-not-officially-supported use of Trusona's core technologies.</dd>
    <dt>Is the data encrypted?</dt>
    <dd>No. We do not encrypt the data entered into the system.</dd>
    <dt>So, you can totally read my messages, right?</dt>
    <dd>Yes. We could, which is why we don't suggest sharing too much context in the secrets.</dd>
    <dt>When will you add feature ________?</dt>
    <dd>Head over to <a href="https://github.com/clayton/secret_snippet/issues">GitHub</a> and add a feature request.</dd>
    <dt>Is it safe to use?</dt>
    <dd>In short, yes. Because we're using Trusona, we know that once you share the link with your friend, only they can access it. With that said, we don't recommend sending too much sensitive information. When you are just sending a password, and there is no context of how it can be used, there isn't much we can do with it.</dd>
    <dt>Can I view the source?</dt>
    <dd>Yes. It's available on <a href="https://github.com/clayton/secret_snippet">GitHub</a>. </dd>
  </dl>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="col">
    <h1 class="font-weight-bold">Need to share a password, API key, URL, or secret family recipe with a friend?</h1>
    <h2 class="mt-1 mb-5">Share a Secret Snippet! It's quick, easy and because we're using <a href="https://www.trusona.com">Trusona's</a> award winning mobile app, it's secure. <strong>Only your friend can unlock the Snippet once you create it.</strong></h2>
  </div>
</div>
<div class="row">
  <div class="col-lg">
    <h3>Quick Start</h3>
    <hr>
    <h4>1. Have your friend download the Trusona App.</h4>
    <p class="ml-4">
      <%= link_to(image_tag("Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", width: "120"), "https://itunes.apple.com/us/app/trusona/id1052983449?mt=8")%>

      <%= link_to(image_tag("google-play-badge.png", width: 120), "https://play.google.com/store/apps/details?id=com.trusona.trusona&amp;pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1")%>
    </p>
    <h4>2. Create a snippet and copy the shareable link.</h4>
    <p class="ml-4"><%= link_to "Create a new Secret Snippet", new_secret_path, class: 'btn btn-light' %></p>
    <h4>3. Share the link and tell your friend.</h4>
    <p class="ml-4">That's it, you're done! 😎</p>
  </div>
  <div class="col-lg">
    <h3>Ready to go? Try it out.</h3>
    <hr>
    <%= render partial: 'secrets/short_form' %>
  </div>
</div>

app/views/secrets/_form.html.erb
    <% if flash[:error].present? %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= form_for @secret, html: {class: "mb-5 needs-validation #{@was_validated}"} do |f| %>
      <div class="form-group">
        <%= f.label :recipient_email, "Who can view this secret?" %>
        <%= f.text_field :recipient_email, class: "form-control form-control-lg #{@recipient_email_valid_class}", placeholder: random_funny_email_address, required: 'required' %>
        <small id="receipient_email_help" class="form-text text-muted">Enter the email address of the person who is allowed to view this secret.</small>
        <div class="invalid-feedback">
          Please specify a recipient email.
        </div>
      </div>
      <div class="form-group">
        <%= f.label :secret, "Password, secret text, private link etc." %>
        <%= f.text_area :secret, rows: "3", class: "form-control", placeholder: "enter your secret here" %>

        <small id="secret_text_help" class="form-text text-muted">Remember, keep it short and out-of-context.</small>
      </div>
      <div class="form-group">
        <%= f.label :expires_at, "Secret expires in" %>
        <%= f.select :expires_at, expires_at_options, {}, class: "form-control" %>
        <small id="expires_at_help" class="form-text text-muted">Secrets are deleted from the database shortly after expiring.</small>
      </div>
      <button type="submit" class="btn btn-lg btn-primary">Get a shareable link</button>
    <% end %>

app/views/secrets/_short_form.html.erb
    <% if flash[:error].present? %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= form_for Secret.new, html: {class: "mb-5 needs-validation"} do |f| %>
      <div class="form-group">
        <%= f.label :recipient_email, "Enter the email your friend used to register in the Trusona App" %>
        <%= f.text_field :recipient_email, class: "form-control form-control-lg", placeholder: "your friend's email address", required: 'required' %>
        <div class="invalid-feedback">
          Please specify your friend's email.
        </div>
      </div>
      <div class="form-group">
        <%= f.label :secret, "Enter the password, secret text, or private link that you want to share" %>
        <%= f.text_area :secret, rows: "3", class: "form-control", placeholder: "your secret" %>
      </div>
      <button type="submit" class="btn btn-lg btn-primary">Get a shareable link</button>
    <% end %>

app/views/secrets/create.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-header">
        Secret Saved
      </div>
      <div class="card-body">
        <h5 class="card-title">Your secret was successfully created.</h5>
        <p class="card-text">Use the link below to share.</p>
        <input name="shareable-url" id="shareable-url" class="form-control" value="<%= secret_url(@secret, protocol: :https) %>">
        <button onclick="copyToClipboard()" class="mt-5 btn btn-lg btn-secondary">Copy to clipboard</button>
        <p class="card-text mt-2"><%= link_to("Or send it in an email", "mailto:#{@email}?subject=[Secret%20Snippet]%20You%20have%20a%20secret%20waiting&body=To%20view%20the%20secret%20click%20here%3A%20#{secret_url(@secret, protocol: :https)}", class: 'btn btn-light') %></p>
      </div>
    </div>
    <p class="mt-4"><%= link_to "Share another secret", root_url %></p>
  </div>
</div>

<script type="text/javascript">
// https://www.w3schools.com/howto/howto_js_copy_clipboard.asp
// Because lazy
function copyToClipboard() {
  /* Get the text field */
  var copyText = document.getElementById("shareable-url");

  /* Select the text field */
  copyText.select();

  /* Copy the text inside the text field */
  document.execCommand("copy");
}
</script>

app/views/secrets/index.html.erb
<div class="row">
  <div class="col">
    <h1 class="mb-2">Your secrets</h1>
    <% if @secrets.count < 1 %>
      <p>Well, it doesn't look like there are any secrets waiting for you. Would you like to <%= link_to "create one", new_secret_path %>?</p>
    <% else %>
      <% @secrets.each do |secret| %>
        <div class="card mb-4">
          <div class="card-header">
            Expires: <%= secret.expires_at %>
          </div>
          <div class="card-body">
            <textarea class="form-control" readonly rows="3"><%= secret.secret %></textarea>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/secrets/new.html.erb
<div class="row">
  <div class="col">
    <h1>Create a Secret</h1>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/secrets/show.html.erb
<div class="row">
  <div class="col">
    <h2>A secret is waiting</h2>
    <p>In order to view this secret, use the Trusona app on iOS or Android.</p>
    <%= link_to "Use Trusona on your phone to view the secret", new_session_url, class: 'btn btn-lg btn-primary' %>
  </div>
</div>